export { default as Add } from "./add.svg"
export { default as Arrow } from "./arrow.svg"
export { default as ChevronDoubleUp } from "./chevronDoubleUp.svg"
export { default as Close } from "./close.svg"
export { default as Minus } from "./minus.svg"
export { default as ShoppingBag } from "./shoppingBag.svg"
