import clsx from "clsx"
import type { NextPage } from "next"
import Head from "next/head"
import questions from "../../data/faq.json"
import features from "../../data/features.json"
import styles from "../../styles/index.module.scss"
import {
	Contacts,
	Faq,
	FeaturesGrid,
	Hero,
	NavigationBar,
	PriceCard,
	SectionLayout,
} from "./components"

const social_contacts: any = [
	{
		twitter: "https://twitter.com/",
	},
	{
		instagram: "https://www.instagram.com",
	},
	{
		facebook: "https://www.facebook.com/st1ll",
	},
	{
		linkedIn: "https://www.linkedin.com/in/dzmitry-ihnatovich-096b8a36/",
	},
]

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Quick menu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700&display=swap"
					rel="stylesheet"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav className="navbar navbar-fixed-top mainNav">
				<NavigationBar />
			</nav>
			<main className={styles.main}>
				<Hero id="intro" className={clsx(styles.section, styles.intro)} />
				{/* Features section */}
				<SectionLayout
					id="features"
					title="Why you should choose our app"
					subTitle="The rise of mobile devices transforms the way we consume information entirely."
					separator={false}
				>
					<FeaturesGrid data={features} />
				</SectionLayout>
				{/* Prices section */}
				<SectionLayout
					id="prices"
					title="Get awesome features, without extra charges"
					subTitle="sub"
					separator={false}
				>
					<div className={styles.prices}>
						<PriceCard />
						<PriceCard />
					</div>
				</SectionLayout>
				<SectionLayout
					id="faq"
					title="Frequently asked questions"
					subTitle="The rise of mobile devices transforms the way we consume information entirely and we need to know how to use it."
					separator={false}
					className={styles.faq}
					bottomMargin={false}
				>
					<Faq data={questions} />
				</SectionLayout>
			</main>

			<footer
				id="contact"
				className={clsx(styles["footer-base-color"], styles["contact-section"])}
			>
				<div className="container">
					<div className="row row-centered">
						<div className="col-md-3 contact-section__contacts">
							{/* <Contacts /> */}
						</div>
						{/*<div className="col-md-3 contact-section__about">*/}
						{/*<AboutUs about_links={about_links}/>*/}
						{/*</div>*/}
					</div>
					<div className="row row-centered social_icons">
						<Contacts contacts={social_contacts} />
					</div>
					<hr />
					<div className="copyright">© 2022 DI team, made with love</div>
					<div className="scroll_top">
						<div className="scroll_top__button" style={{ display: "block" }}>
							<span className="tooltip">Scroll To Top</span>
						</div>
					</div>
				</div>
			</footer>
		</div>
	)
}

export default Home
