import clsx from "clsx"
import type { NextPage } from "next"
import Head from "next/head"
// import { SocialContacts } from "../types"
import styles from "../../styles/Welcome.module.css"
import { Contacts, NavigationBar, PriceCard } from "./components"

const social_contacts: any = [
	{
		twitter: "https://twitter.com/",
	},
	{
		instagram: "https://www.instagram.com",
	},
	{
		facebook: "https://www.facebook.com/st1ll",
	},
	{
		linkedIn: "https://www.linkedin.com/in/dzmitry-ihnatovich-096b8a36/",
	},
]

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Quick menu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav className="navbar navbar-fixed-top mainNav">
				<NavigationBar />
			</nav>
			<main className={styles.main}>
				<section id="intro" className={styles.intro}>
					<div className="welcome-header col-md-10 col-centered ">
						<h1>Best app for managing your online menu</h1>
						<p>
							Make life of your client easier and bring ideal service in
							restaurant business
						</p>
					</div>
					{/* <div className="container">
						<div className="row row-centered">
							<div className="welcome-header col-md-10 col-centered ">
							
								<h1
									className="text-upper-case"
									style={{ paddingBottom: "20px" }}
								>
									Лучший способ управления своим бизнесом
								</h1>
							</div>
							<div className="welcome-text col-md-8 col-centered">
								<p>
									Андромеда фитнес позволит легко управлять тренажерным залом,
									автоматизируя все необходимые операции, а также предоставляя
									возможность управления посещениями в один клик
								</p>
							</div>
						</div>
					</div> */}
				</section>

				{/* Prices section */}
				<section id="prices" className="prices-section">
					<div className="container">
						<div className="row row-centered">
							<div className="col-md-8 col-centered section-header">
								<h1 className="text-upper-case">
									Get awesome features, without extra charges
								</h1>
								<div>{/* <Switch/> */}</div>
								<hr />
							</div>
						</div>
						<div className="row price-row">
							<div className="col-xs-12 col-sm-4 price_col">
								{/* <PriceComponent price="Бесплатно" tariffName="Базовый" popular={true} onClick={this.onSignUpCall} duration="30 дней"/> */}
							</div>
							{/*<div className="col-xs-12 col-sm-4 price_col">*/}
							{/*<PriceComponent popular tariffName="Standart" onClick={this.onSignUpCall}/>*/}
							{/*</div>*/}
							{/*<div className="col-xs-12 col-sm-4 price_col">*/}
							{/*<PriceComponent tariffName="Premium" onClick={this.onSignUpCall}/>*/}
							{/*</div>*/}
						</div>
					</div>
				</section>

				{/* Satisfaction section */}
				<section id="satisfaction" className="prices-section">
					<div className="container">
						<div className="row row-centered">
							<div className="col-md-8 col-centered section-header">
								<h1 className="text-upper-case">
									Get awesome features, without extra charges
								</h1>
								<PriceCard />
								<hr />
							</div>
						</div>
						<div className="row price-row">
							<div className="col-xs-12 col-sm-4 price_col">
								{/* <PriceComponent price="Бесплатно" tariffName="Базовый" popular={true} onClick={this.onSignUpCall} duration="30 дней"/> */}
							</div>
							{/*<div className="col-xs-12 col-sm-4 price_col">*/}
							{/*<PriceComponent popular tariffName="Standart" onClick={this.onSignUpCall}/>*/}
							{/*</div>*/}
							{/*<div className="col-xs-12 col-sm-4 price_col">*/}
							{/*<PriceComponent tariffName="Premium" onClick={this.onSignUpCall}/>*/}
							{/*</div>*/}
						</div>
					</div>
				</section>
				{/* <p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/master/examples"
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div> */}
			</main>

			<footer
				id="contact"
				className={clsx(styles["footer-base-color"], styles["contact-section"])}
			>
				<div className="container">
					<div className="row row-centered">
						<div className="col-md-3 contact-section__contacts">
							{/* <Contacts /> */}
						</div>
						{/*<div className="col-md-3 contact-section__about">*/}
						{/*<AboutUs about_links={about_links}/>*/}
						{/*</div>*/}
					</div>
					<div className="row row-centered social_icons">
						<Contacts contacts={social_contacts} />
					</div>
					<hr />
					<div className="copyright">© 2022 DI team, made with love</div>
					<div className="scroll_top">
						<div className="scroll_top__button" style={{ display: "block" }}>
							<span className="tooltip">Scroll To Top</span>
						</div>
					</div>
				</div>
			</footer>
		</div>
	)
}

export default Home
